import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-4 gap-6">
          <Link href={"/schedule"} className="text-white p-6 text-2xl">Week Schedule</Link>
          <Link href={"/buisnessInfo"} className="text-white p-6 text-2xl">Buisness Info</Link>
        </div>
        


        {children}
      </body>
    </html>
  );
}
